server/apps/identity/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from server.apps.identity.views.login import LoginView, RegistrationView
from server.apps.identity.views.user import UserUpdateView

app_name = 'identity'

urlpatterns = [
    # Login mechanics:
    path(
        'login',
        LoginView.as_view(template_name='identity/pages/login.html'),
        name='login',
    ),
    path('logout', LogoutView.as_view(), name='logout'),
    path('registration', RegistrationView.as_view(), name='registration'),

    # User updating:
    path('update', UserUpdateView.as_view(), name='user_update'),
]

server/apps/pictures/urls.py
from django.urls import path

from server.apps.pictures.views import DashboardView, FavouritePicturesView, FavouriteDeleteView

app_name = 'pictures'

urlpatterns = [
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('favourites', FavouritePicturesView.as_view(), name='favourites'),
    path('favourites/<int:picture_id>', FavouriteDeleteView.as_view(), name='remove_favourite'),
]

server/urls.py
"""
Main URL mapping configuration file.

Include other URLConfs from external apps using method `include()`.

It is also a good practice to keep a single URL to the root index page.

This examples uses Django's default media
files serving technique in development.
"""

from django.conf import settings
from django.contrib import admin
from django.contrib.admindocs import urls as admindocs_urls
from django.urls import include, path
from django.views.generic import TemplateView
from health_check import urls as health_urls

from server.apps.identity import urls as identity_urls
from server.apps.pictures import urls as pictures_urls
from server.apps.pictures.views import IndexView
import debug_toolbar  # noqa: I001

admin.autodiscover()

urlpatterns = [
    # Apps:
    path('pictures/', include(pictures_urls, namespace='pictures')),
    path('identity/', include(identity_urls, namespace='identity')),

    # Health checks:
    path('health/', include(health_urls)),

    # django-admin:
    path('admin/doc/', include(admindocs_urls)),
    path('admin/', admin.site.urls),

    # Text and xml static files:
    path('robots.txt', TemplateView.as_view(
        template_name='common/txt/robots.txt',
        content_type='text/plain',
    )),
    path('humans.txt', TemplateView.as_view(
        template_name='common/txt/humans.txt',
        content_type='text/plain',
    )),

    # It is a good practice to have an explicit index view:
    path('', IndexView.as_view(), name='index'),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar  # noqa: WPS440 WPS433
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns = [
        # URLs specific only to django-debug-toolbar:
        path('__debug__/', include(debug_toolbar.urls)),
        *urlpatterns,
        # Serving media files in development only:
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ]

server/apps/pictures/models.py
from typing import final

from django.conf import settings
from django.db import models

from server.common.django.models import TimedMixin


@final
class FavouritePicture(TimedMixin, models.Model):
    """Represents a :term:`picture` saved in :term:`favourites`."""

    # Linking:
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='pictures',
        on_delete=models.CASCADE,
    )

    # Data:
    foreign_id = models.IntegerField()
    url = models.URLField()

    def __str__(self) -> str:
        """Beautiful representation."""
        return '<Picture {0} by {1}>'.format(self.foreign_id, self.user_id)

server/common/django/models.py
from django.db import models


class TimedMixin(models.Model):
    """Adding utility time fields for different models."""

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta(object):
        abstract = True

server/apps/pictures/infrastructure/django/forms.py
from typing import Any, final

from django import forms

from server.apps.pictures.models import FavouritePicture


@final
class FavouritesForm(forms.ModelForm[FavouritePicture]):
    """Model form for :class:`FavouritePicture`."""

    class Meta(object):
        model = FavouritePicture
        fields = ('foreign_id', 'url')

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """We need an extra context: which user is adding items."""
        self._user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self, commit: bool = True) -> FavouritePicture:
        """Add user to the model instance."""
        instance = super().save(commit=False)
        instance.user_id = self._user.id
        if commit:
            instance.save()
        return instance

server/common/django/forms.py
from django import forms


class DateWidget(forms.DateInput):
    """Date input in the proper date format."""

    input_type = 'date'
    format = '%Y-%m-%d'  # noqa: WPS323

server/apps/pictures/views.py
from typing import Any, final

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import QuerySet
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, TemplateView

from server.apps.pictures.container import container
from server.apps.pictures.infrastructure.django.forms import FavouritesForm
from server.apps.pictures.logic.usecases import favourites_list, pictures_fetch
from server.apps.pictures.models import FavouritePicture
from server.common.django.decorators import dispatch_decorator


@final
class IndexView(TemplateView):
    """
    View the :term:`laning`.

    It is a main page open for everyone.
    """

    template_name = 'pictures/pages/index.html'


@final
@dispatch_decorator(login_required)
class DashboardView(CreateView[FavouritePicture, FavouritesForm]):
    """
    View the :term:`dashboard`.

    It is a main page of the whole application.
    This is where we show :term:`pictures` to be saved in :term:`favourites`.
    """

    form_class = FavouritesForm
    template_name = 'pictures/pages/dashboard.html'
    success_url = reverse_lazy('pictures:dashboard')

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """Inject extra context to template rendering."""
        fetch_pictures = container.instantiate(pictures_fetch.PicturesFetch)

        context = super().get_context_data(**kwargs)
        context['pictures'] = fetch_pictures()  # sync http call, may hang
        return context

    def get_form_kwargs(self) -> dict[str, Any]:
        """Add current user to the context."""
        base_kwargs = super().get_form_kwargs()
        base_kwargs['user'] = self.request.user
        return base_kwargs

    def form_valid(self, form: FavouritesForm) -> HttpResponse:
        """Data is valid: show a message about it."""
        messages.success(self.request, 'Добавлено')
        return super().form_valid(form)


@final
@dispatch_decorator(login_required)
class FavouritePicturesView(ListView[FavouritePicture]):
    """View the :term:`favourites`."""

    template_name = 'pictures/pages/favourites.html'

    def get_queryset(self) -> QuerySet[FavouritePicture]:
        """Return matching pictures."""
        list_favourites = container.instantiate(favourites_list.FavouritesList)
        return list_favourites(self.request.user.id)

server/apps/pictures/templates/pictures/pages/dashboard.html
{% extends 'common/_base.html' %}

{% load static %}

{% block title %}
  Testing Homework
{% endblock title %}
{% block content %}
  <main>
    <article>
      <h3>Профиль</h3>
      <ul>
        <li>
          <span>ФИО:</span>
          <span>{{ user.first_name }} {{ user.last_name }}</span>
        </li>
        <li>
          <span>Дата рождения:</span>
          <span>{{ user.date_of_birth|stringformat:'s' }}</span>
        </li>
        <li>
          <span>Страна, город:</span>
          <span>{{ user.address }}</span>
        </li>
        <li>
          <span>Должность:</span>
          <span>{{ user.job_title }}</span>
        </li>
        <li>
          <span>Телефон:</span>
          <span>{{ user.phone }}</span>
        </li>
        <li>
          <span>Электронная почта:</span>
          <span>{{ user.email }}</span>
        </li>
      </ul>
      <a href="{% url 'identity:user_update' %}">Изменить</a>
    </article>
    <article>
      <div>
        {% include 'common/includes/messages.html' with messages=messages %}
        {{ form.errors }}
      </div>
      {% for picture in pictures %}
        <div data-test-id="picture-fecthed-item">
          <img alt="Картинка {{ picture.id }}" src="{{ picture.url }}" />
          <form method="post" action="{% url 'pictures:dashboard' %}">
            {% csrf_token %}
            <input type="hidden" name="foreign_id" value="{{ picture.id }}" />
            <input type="hidden" name="url" value="{{ picture.url }}" />
            <button type="submit">Добавить в избранное</button>
          </form>
          <form method="post" action="{% url 'pictures:remove_favourite' picture_id=picture.id %}">
            {% csrf_token %}
            <button type="submit">Удалить из избранного</button>
          </form>
        </div>
        <hr />
      {% endfor %}
    </article>
  </main>
{% endblock content %}

server/apps/pictures/templates/pictures/pages/favourites.html
{% extends 'common/_base.html' %}

{% load static %}

{% block title %}
  Запись на консультацию с основателем
{% endblock title %}
{% block content %}
  <main>
    <h1>Список любимых картинок</h1>
    {% for picture in object_list %}
      <div data-test-id="favourites-picture-db">
        <p>Номер {{ picture.foreign_id }}</p>
        <img alt="Картинка {{ picture.foreign_id }}" src="{{ picture.url }}" />
      </div>
    {% endfor %}
  </main>
{% endblock content %}

server/apps/pictures/templates/pictures/pages/index.html
{% extends 'common/_base.html' %}

{% load static %}

{% block title %}
  Привет!
{% endblock title %}
{% block content %}
  <main>
    <h1>Добро пожаловать в домашнее задание в курсе по тестированию.</h1>
    <h2>В чем суть?</h2>
    <p>
      Тут мы делаем простое приложение:
      <ol>
        <li>Регистрация и логин пользователя</li>
        <li>Получение картинок из стороннего ресурса</li>
        <li>Возможность локально сохранять ссылки на самые любимые</li>
      </ol>
    </p>
  </main>
{% endblock content %}

server/common/django/templates/common/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css" />
  </head>
  <body>
    <div>
      {% include 'common/includes/header.html' %}
      {% block content %}
      {% endblock content %}
    </div>
    {% include 'common/includes/footer.html' %}
  </body>
</html>

server/common/django/templates/common/includes/field.html
{% load static %}

<div>
  <label for="{{ field.id_for_label }}">{{ field_label }}</label>
  <input placeholder=""
         type="{{ field.field.widget.input_type }}"
         id="{{ field.id_for_label }}"
         name="{{ field.name }}"
         {% if field.field.required %}required{% endif %}
         {% if not field.value or field.field.widget.input_type == 'password' %}
           value=""
         {% else %}
           value="{{ field.value|stringformat:'s' }}"
         {% endif %} />
  {% if field.errors %}<div>{{ field.errors }}</div>{% endif %}
</div>

server/common/django/templates/common/includes/footer.html
{% load static %}

<footer class="footer">
  <p>Have fun!</p>
</footer>

server/common/django/templates/common/includes/header.html
<header>
  <nav>
    <ul>
      <li>
        <a href="{% url 'index' %}">Главная</a>
      </li>
      {% if user.is_authenticated %}
        <li>
          <a href="{% url 'pictures:dashboard' %}">Личный кабинет</a>
        </li>
        <li>
          <a href="{% url 'pictures:favourites' %}">Любимые картинки</a>
        </li>
        <li>
          <a href="{% url 'identity:logout' %}">Выход</a>
        </li>
      {% else %}
        <li>
          <a href="{% url 'identity:login' %}">Войти</a>
        </li>
        <li>
          <a href="{% url 'identity:registration' %}">Регистрация</a>
        </li>
      {% endif %}
    </ul>
  </nav>
</header>

server/common/django/templates/common/includes/messages.html
{% if messages %}
  {% for message in messages %}
    {# We don't have any non-successful messages just yet #}
    <p>{{ message }}</p>
  {% endfor %}
{% endif %}